In [17]:
import numpy as np

In [3]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [4]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [5]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [7]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [9]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

# option 2

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 12. Create a 3x3x3 array with random values

random_arr = np.random.random((3,4,3))
print(random_arr)

[[[0.16538514 0.14584791 0.93690662]
  [0.93413073 0.54169771 0.69580472]
  [0.5470568  0.25962768 0.49927508]
  [0.95018749 0.28925007 0.64044758]]

 [[0.52399177 0.9417617  0.61841214]
  [0.86540271 0.42117314 0.78526403]
  [0.19957366 0.24479471 0.93808486]
  [0.95387598 0.46542103 0.2432279 ]]

 [[0.20093605 0.08880825 0.46933399]
  [0.50942366 0.75653316 0.82517064]
  [0.75276416 0.73464403 0.18427251]
  [0.25899448 0.10687198 0.28724948]]]


In [11]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

mx_min_arr = np.random.random((10,10))
print(mx_min_arr)

print("Min value is: ", mx_min_arr.min())
print("Max value is: ", mx_min_arr.max())


[[0.05249686 0.79093996 0.84563619 0.21210177 0.43746433 0.97403373
  0.68490041 0.19557482 0.77386723 0.25200948]
 [0.9417277  0.30352927 0.83000869 0.69273524 0.610652   0.37961405
  0.96666225 0.83630153 0.73634732 0.169674  ]
 [0.5575515  0.48906633 0.24180579 0.60124831 0.50154035 0.73254067
  0.70885406 0.63296475 0.57372589 0.03004826]
 [0.74400587 0.91085987 0.33077574 0.76793042 0.01743831 0.76102664
  0.9533745  0.79101057 0.9839287  0.78587429]
 [0.59910429 0.15708542 0.9206051  0.10499092 0.47612585 0.70562308
  0.79472364 0.77203254 0.42886267 0.19208756]
 [0.23050905 0.52438232 0.57803253 0.44793512 0.91386411 0.65173839
  0.08197468 0.78286012 0.61153831 0.19617301]
 [0.07890901 0.75832711 0.52419275 0.34083247 0.03469534 0.84315813
  0.61082416 0.59608166 0.88534189 0.1286175 ]
 [0.55373532 0.1657345  0.55179316 0.6466502  0.37126448 0.67047298
  0.98243501 0.05321086 0.532113   0.95767186]
 [0.54202696 0.04807305 0.62626498 0.51098024 0.87697567 0.05879551
  0.90805407

In [12]:
# 14. Create a random vector of size 30 and find the mean value

ran_vec = np.random.random((30))
print(ran_vec)

print("min vector value is: ", ran_vec.min())

[0.23642347 0.72220941 0.88577923 0.52881488 0.19591231 0.94787507
 0.19053368 0.97277474 0.40668104 0.47028862 0.405811   0.21506282
 0.93566279 0.03865392 0.31436485 0.11272897 0.61926319 0.67376736
 0.58177797 0.67894397 0.12851071 0.041057   0.93519273 0.78435761
 0.07273566 0.21540894 0.14565504 0.11616797 0.74190231 0.16539802]
min vector value is:  0.038653923150884895


In [13]:
# 15. Create a 2d array with 1 on the border and 0 inside

twoDarr = np.ones((5,5))

twoDarr[1:-1, 1:-1] = 0
print(twoDarr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# 16. How to add a border (filled with 0's) around an existing array?
twoD = np.zeros((5,5))
 print(twoD)

IndentationError: unexpected indent (1408128628.py, line 3)

In [ ]:
diag = np.diag([1,2,3,4], k= -1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# 18  Create a 8x8 matrix and fill it with a checkerboard pattern

checkboard = np.zeros((8,8), dtype= int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
# another way

cbd = np.indices((8,8)).sum(axis= 0) % 2
print(cbd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 20 Create a checkerboard 8x8 matrix using the tile function

tileprob = np.array([[1,0],
					[0,1]])
answ = np.tile(tileprob, (8,8))
print(answ)

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [ ]:
# 21 Normalize a 5x5 random matrix 
orgarr = np.random.random((5,5))

norarr = (orgarr - orgarr.min() / orgarr.max() - orgarr.min())


print("Original Array: ", orgarr)
print("\nNormalized Array: ", norarr)


Original Array:  [[0.92277896 0.52235666 0.40271386 0.80461363 0.78983582]
 [0.99289148 0.13787267 0.00320727 0.41792816 0.38437367]
 [0.91737789 0.20771584 0.42238571 0.624296   0.63530621]
 [0.31490825 0.73147836 0.15127435 0.10504759 0.10832823]
 [0.02670801 0.57355069 0.74075975 0.16777669 0.79427153]]

Normalized Array:  [[ 0.91634146  0.51591916  0.39627636  0.79817613  0.78339832]
 [ 0.98645398  0.13143517 -0.00323023  0.41149066  0.37793616]
 [ 0.91094039  0.20127834  0.41594821  0.61785849  0.62886871]
 [ 0.30847075  0.72504086  0.14483685  0.09861009  0.10189073]
 [ 0.02027051  0.56711319  0.73432225  0.16133918  0.78783403]]


: 

In [ ]:
# 23

color_dtype = np.dtype([
	('R', np.uint8),
	('G', np.uint8),
	('B', np.uint8),
	('A', np.uint8)
])

In [ ]:
color = np.array((255, 128, 64, 255), dtype= color_dtype)
print(color)

(255, 128, 64, 255)


In [ ]:
print(color['R'])

255


In [ ]:
# 24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

m1 = np.random.random((5, 3))
m2 = np.random.random((3, 2))

res = np.dot(m1, m2)

print("Matrix A: ", m1)
print("Matrix B: ", m2)
print("Matrix product: ", res)

Matrix A:  [[0.09351657 0.14138867 0.18985749]
 [0.78778939 0.76493711 0.27755915]
 [0.9703745  0.64998626 0.91879054]
 [0.69099934 0.113891   0.89807111]
 [0.73755635 0.12872484 0.1000381 ]]
Matrix B:  [[0.7600775  0.95274675]
 [0.43794549 0.22345285]
 [0.2000696  0.41077895]]
Matrix product:  [[0.17098509 0.19868077]
 [0.9893129  1.03550662]
 [1.20604043 1.44718225]
 [0.75476782 1.05270535]
 [0.63698903 0.77256189]]


In [ ]:
# 25 
arrneg = np.array([1, 4, 6, 9, 2, 7, 8, 3])

arrneg[(arrneg > 3) & (arrneg < 8)] *= -1

print(arrneg)


[ 1 -4 -6  9  2 -7  8  3]


In [ ]:
# 27

z = np.array([1,2,3])

print(z**z) # legal

[ 1  4 27]


In [ ]:
# 28

test = np.array([np.nan]).astype(int).astype(float)

print(test)

[-9.22337204e+18]


C:\Users\santosh\AppData\Local\Temp\ipykernel_1624\1126788739.py:3: RuntimeWarning: invalid value encountered in cast
  test = np.array([np.nan]).astype(int).astype(float)


In [ ]:
# 29
roundarr = np.array([1.2, -2.1, 3.1, -4.2, 2.3, -1.1])

rounded = np.sign(roundarr) * np.ceil(np.abs(roundarr))

print(rounded)

[ 2. -3.  4. -5.  3. -2.]


In [ ]:
# 30
A = np.array([1,2,9,8,5])
B = np.array([6,7,8,9,10])

common = np.intersect1d(A, B)
print(common)

[8 9]


In [18]:
# 31 How to ignore all numpy warnings (not recommended)?
# ignp = np.seterr(all='ignore')

from datetime import date, timedelta

In [20]:


today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)

Yesterday:  2026-02-01
Today:  2026-02-02
Tomorrow:  2026-02-03
