In [1]:
import numpy as np

In [2]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [3]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [4]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [8]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

# option 2

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# 12. Create a 3x3x3 array with random values

random_arr = np.random.random((3,4,3))
print(random_arr)

[[[0.7306763  0.84154011 0.97974431]
  [0.94933617 0.46472396 0.0442857 ]
  [0.06442343 0.70093583 0.9573806 ]
  [0.76696494 0.6714844  0.49740793]]

 [[0.26543442 0.16065847 0.10191307]
  [0.71848551 0.97567151 0.12736419]
  [0.72066437 0.67351998 0.91750824]
  [0.10027282 0.7195927  0.24411652]]

 [[0.48213115 0.62002335 0.89234   ]
  [0.34609901 0.84294429 0.18511972]
  [0.23407081 0.12536873 0.21842756]
  [0.76672659 0.59905537 0.1310053 ]]]


In [10]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

mx_min_arr = np.random.random((10,10))
print(mx_min_arr)

print("Min value is: ", mx_min_arr.min())
print("Max value is: ", mx_min_arr.max())


[[0.11516044 0.21329673 0.65885245 0.83250434 0.33227337 0.33685444
  0.30543006 0.05704504 0.90977423 0.50650403]
 [0.88557168 0.75103128 0.67970386 0.85598887 0.52633378 0.27385547
  0.4764059  0.85437653 0.14097966 0.38635652]
 [0.95358952 0.89509089 0.39122334 0.94354676 0.26322333 0.09723858
  0.17385678 0.59251794 0.337956   0.1010843 ]
 [0.37430552 0.79699247 0.76862488 0.97029842 0.73780194 0.5427645
  0.22795314 0.48995065 0.98082818 0.20127403]
 [0.01009632 0.99399895 0.19846264 0.24978667 0.58711067 0.06401491
  0.37772625 0.00586612 0.17404256 0.01042107]
 [0.48654319 0.61146537 0.55731557 0.76491547 0.52177255 0.15498334
  0.3258933  0.92397774 0.04178139 0.9665652 ]
 [0.87019205 0.08024566 0.77327896 0.54682277 0.25611241 0.69619048
  0.96124997 0.25362293 0.15986084 0.38291499]
 [0.27147041 0.39980802 0.16338495 0.69958589 0.1334236  0.65887407
  0.35577875 0.49861655 0.53266181 0.67726707]
 [0.05237022 0.81649788 0.14512671 0.00763614 0.41716576 0.3274884
  0.23590084 0

In [11]:
# 14. Create a random vector of size 30 and find the mean value

ran_vec = np.random.random((30))
print(ran_vec)

print("min vector value is: ", ran_vec.min())

[0.75937478 0.22022124 0.2717032  0.14753427 0.276282   0.94663089
 0.86697781 0.00924379 0.20239405 0.63923209 0.45270108 0.16206361
 0.66548739 0.97028874 0.62734743 0.56272843 0.53913947 0.84393507
 0.75320547 0.93626241 0.39445043 0.46314596 0.0957862  0.34947273
 0.49477205 0.51356928 0.22480701 0.0986268  0.86877147 0.19192862]
min vector value is:  0.009243793745831508


In [12]:
# 15. Create a 2d array with 1 on the border and 0 inside

twoDarr = np.ones((5,5))

twoDarr[1:-1, 1:-1] = 0
print(twoDarr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# 16. How to add a border (filled with 0's) around an existing array?
twoD = np.zeros((5,5))
 print(twoD)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
diag = np.diag([1,2,3,4], k= -1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [25]:
# 18  Create a 8x8 matrix and fill it with a checkerboard pattern

checkboard = np.zeros((8,8), dtype= int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [27]:
# another way

cbd = np.indices((8,8)).sum(axis= 0) % 2
print(cbd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
