In [13]:
import numpy as np

In [14]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [15]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [16]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [19]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [23]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
