In [1]:
import numpy as np

In [2]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [3]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [4]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [8]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

# option 2

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# 12. Create a 3x3x3 array with random values

random_arr = np.random.random((3,4,3))
print(random_arr)

[[[0.04208102 0.57293399 0.41237632]
  [0.49844743 0.30573673 0.75874842]
  [0.45893029 0.94382997 0.46736564]
  [0.73554839 0.13812704 0.75580955]]

 [[0.59397357 0.74250569 0.13895216]
  [0.09203911 0.79405187 0.08790183]
  [0.98723171 0.68546392 0.69298612]
  [0.79183086 0.95918917 0.25325755]]

 [[0.40525608 0.9813319  0.58297953]
  [0.67441042 0.91586232 0.36738681]
  [0.09735777 0.97705481 0.3176317 ]
  [0.29920298 0.21756532 0.8368408 ]]]


In [10]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

mx_min_arr = np.random.random((10,10))
print(mx_min_arr)

print("Min value is: ", mx_min_arr.min())
print("Max value is: ", mx_min_arr.max())


[[0.80187176 0.15184359 0.42384133 0.51311181 0.36481775 0.32140261
  0.96550012 0.08150986 0.20357722 0.2804713 ]
 [0.63023822 0.49197302 0.83662107 0.72843049 0.02071982 0.94915956
  0.27561024 0.61957309 0.79862929 0.23300445]
 [0.3780556  0.47200132 0.91629698 0.72289934 0.76656394 0.01142607
  0.0876448  0.7348795  0.44416916 0.41354895]
 [0.52892928 0.8112229  0.84192284 0.83306816 0.38559342 0.34044933
  0.83748982 0.32750802 0.9557947  0.82458975]
 [0.37086703 0.05942885 0.21638183 0.70204264 0.94763455 0.17875261
  0.83378274 0.86940789 0.88269413 0.25853983]
 [0.06350164 0.32844036 0.42376549 0.72395766 0.84553602 0.40132746
  0.6597073  0.5932099  0.48060906 0.266028  ]
 [0.22773114 0.21068957 0.5149934  0.08241563 0.49126685 0.70560468
  0.47543923 0.46152729 0.99538393 0.15456136]
 [0.69964653 0.04792158 0.27124562 0.19387416 0.62018622 0.28141619
  0.47765578 0.5392122  0.94378446 0.35756664]
 [0.6102092  0.49029968 0.62856016 0.50479839 0.63125013 0.8466706
  0.40060696 

In [11]:
# 14. Create a random vector of size 30 and find the mean value

ran_vec = np.random.random((30))
print(ran_vec)

print("min vector value is: ", ran_vec.min())

[0.87292787 0.03178542 0.93334277 0.75942017 0.50522096 0.26128367
 0.093813   0.68070473 0.39234768 0.66174364 0.54400767 0.52906736
 0.62155194 0.57636152 0.79522239 0.86197114 0.06804633 0.78410814
 0.21188509 0.30908316 0.07865861 0.45137562 0.39320613 0.61867904
 0.49782866 0.77741049 0.61515913 0.65883853 0.21604323 0.51106598]
min vector value is:  0.03178542102849524


In [12]:
# 15. Create a 2d array with 1 on the border and 0 inside

twoDarr = np.ones((5,5))

twoDarr[1:-1, 1:-1] = 0
print(twoDarr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# 16. How to add a border (filled with 0's) around an existing array?
twoD = np.zeros((5,5))
print(twoD)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
diag = np.diag([1,2,3,4], k= -1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [15]:
# 18  Create a 8x8 matrix and fill it with a checkerboard pattern

checkboard = np.zeros((8,8), dtype= int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [16]:
# another way

cbd = np.indices((8,8)).sum(axis= 0) % 2
print(cbd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# 20 Create a checkerboard 8x8 matrix using the tile function

tileprob = np.array([[1,0],
					[0,1]])
answ = np.tile(tileprob, (8,8))
print(answ)

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [18]:
# 21 Normalize a 5x5 random matrix 
orgarr = np.random.random((5,5))

norarr = (orgarr - orgarr.min() / orgarr.max() - orgarr.min())


print("Original Array: ", orgarr)
print("\nNormalized Array: ", norarr)


Original Array:  [[0.00559703 0.78552443 0.88513616 0.3341121  0.57862282]
 [0.50493677 0.52398281 0.13096045 0.4528891  0.87956373]
 [0.73247691 0.6893842  0.63138675 0.58220862 0.43670179]
 [0.45964752 0.15790855 0.08391098 0.91029969 0.19878308]
 [0.85082347 0.09323268 0.60643348 0.63432504 0.44159537]]

Normalized Array:  [[-0.00614855  0.77377885  0.87339058  0.32236652  0.56687724]
 [ 0.49319119  0.51223723  0.11921487  0.44114352  0.86781815]
 [ 0.72073133  0.67763862  0.61964117  0.57046303  0.42495621]
 [ 0.44790194  0.14616297  0.0721654   0.89855411  0.1870375 ]
 [ 0.83907789  0.0814871   0.5946879   0.62257946  0.42984979]]


In [19]:
# 23

color_dtype = np.dtype([
	('R', np.uint8),
	('G', np.uint8),
	('B', np.uint8),
	('A', np.uint8)
])

In [20]:
color = np.array((255, 128, 64, 255), dtype= color_dtype)
print(color)

(255, 128, 64, 255)


In [21]:
print(color['R'])

255


In [22]:
# 24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

m1 = np.random.random((5, 3))
m2 = np.random.random((3, 2))

res = np.dot(m1, m2)

print("Matrix A: ", m1)
print("Matrix B: ", m2)
print("Matrix product: ", res)

Matrix A:  [[0.31333938 0.14889611 0.39983027]
 [0.04503132 0.05303143 0.1373051 ]
 [0.83964116 0.19732569 0.83673132]
 [0.972276   0.47902585 0.34817452]
 [0.7330507  0.03670192 0.97550599]]
Matrix B:  [[0.58902519 0.45230519]
 [0.11451778 0.06356286]
 [0.38522697 0.90689998]]
Matrix product:  [[0.35564144 0.51379536]
 [0.08549125 0.14826072]
 [0.83949856 1.15114825]
 [0.76167825 0.78597319]
 [0.81177956 1.21858187]]


In [23]:
# 25 
arrneg = np.array([1, 4, 6, 9, 2, 7, 8, 3])

arrneg[(arrneg > 3) & (arrneg < 8)] *= -1

print(arrneg)


[ 1 -4 -6  9  2 -7  8  3]


In [24]:
# 27

z = np.array([1,2,3])

print(z**z) # legal

[ 1  4 27]


In [25]:
# 28

test = np.array([np.nan]).astype(int).astype(float)

print(test)

[-9.22337204e+18]


C:\Users\santosh\AppData\Local\Temp\ipykernel_7880\1949928742.py:3: RuntimeWarning: invalid value encountered in cast
  test = np.array([np.nan]).astype(int).astype(float)


In [26]:
# 29
roundarr = np.array([1.2, -2.1, 3.1, -4.2, 2.3, -1.1])

rounded = np.sign(roundarr) * np.ceil(np.abs(roundarr))

print(rounded)

[ 2. -3.  4. -5.  3. -2.]


In [27]:
# 30
A = np.array([1,2,9,8,5])
B = np.array([6,7,8,9,10])

common = np.intersect1d(A, B)
print(common)

[8 9]


In [28]:
# 31 How to ignore all numpy warnings (not recommended)?
# ignp = np.seterr(all='ignore')

from datetime import date, timedelta

In [29]:


today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)

Yesterday:  2026-02-05
Today:  2026-02-06
Tomorrow:  2026-02-07


In [30]:
# 34 How to get all the dates corresponding to the month of July 2016?
start = date(2016, 7, 1)
end = date(2016, 8, 1)

dates = []
current = start

while (current < end):
	dates.append(current)
	current += timedelta(days=1)

print(dates)

[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


In [31]:
# 36  Extract the integer part of a random array of positive numbers using 4 different methods
arr = np.random.random(5) * 10
print(arr)

[1.93976151 2.43066154 9.88664107 5.90266663 6.29919065]


In [32]:
# 1. using floor

arrfloor = np.floor(arr)
print(arrfloor)

# 2. using astype

arrtype = arr.astype(int)
print(arrtype)


[1. 2. 9. 5. 6.]
[1 2 9 5 6]


In [33]:
# 3. using trunc

arrtrunc = np.trunc(arr)

print(arrtrunc)

[1. 2. 9. 5. 6.]


In [34]:
# 4. using int divison

arrdivision = arr // 1

print(arrdivision)

[1. 2. 9. 5. 6.]


In [35]:
# 37 Create a 5x5 matrix with row values ranging from 0 to 4 

arrtile = np.tile(np.arange(5), (5,1))
print(arrtile)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [36]:
# 38 Consider a generator function that generates 10 integers and use it to build an array
def gen_gerenter():
	for i in range(10):
		yield i

In [37]:
gen_num = np.fromiter(gen_gerenter(), dtype=int)
print(gen_num)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
# 39
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [39]:
# 40 Create a random vector of size 10 and sort it

rvec = np.random.random(10)
srt = np.sort(rvec)

print("Original array: ",rvec)
print("Sorted array: ",srt)

Original array:  [0.46845157 0.84736428 0.1003468  0.76751441 0.05288908 0.13371565
 0.14646939 0.51333089 0.36428228 0.55844634]
Sorted array:  [0.05288908 0.1003468  0.13371565 0.14646939 0.36428228 0.46845157
 0.51333089 0.55844634 0.76751441 0.84736428]


In [40]:
# 41  How to sum a small array faster than np.sum?

samplearr = np.array([1,2,3,4,5])

# using numpy
npsum = np.sum(samplearr)
print(npsum)

# using built-in 
bisum = sum(samplearr)
print(bisum)

15
15


In [41]:
# 42 Consider two random arrays A and B, check if they are equal

A = np.random.random(5)
B = np.random.random(5)

isequal = np.allclose(A, B)

print(isequal)

False


In [42]:
# 43 Make an array immutable (read-only) 

arr = np.array([1,2,3,4,5])
imutable = arr.flags.writeable = False


In [45]:
# 45  Create random vector of size 10 and replace the maximum value by 0

arr = np.random.random((10))

vec = arr.argmax()

arr[vec] = 0

print(arr)

[0.4817309  0.21180713 0.42296451 0.31134886 0.35332776 0.
 0.60631804 0.37627299 0.41901936 0.76586961]


In [ ]:
# 46  Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

x = np.linspace(0,1, 5)
y = np.linspace(0,1, 5)

x, y = np.meshgrid(x, y)

z = np.zeros(x.size, dtype=[('x', float), ('y', float)])



print(z)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]
