In [2]:
import numpy as np

In [4]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [5]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [6]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [10]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

# option 2

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# 12. Create a 3x3x3 array with random values

random_arr = np.random.random((3,4,3))
print(random_arr)

[[[0.99294563 0.76841895 0.88735902]
  [0.52768826 0.22053187 0.48423329]
  [0.22842077 0.48769757 0.77025818]
  [0.98757185 0.31384094 0.0145034 ]]

 [[0.54722203 0.23117112 0.98423772]
  [0.06161077 0.07213349 0.98214881]
  [0.33064744 0.06687595 0.28982409]
  [0.10229217 0.50835671 0.39515705]]

 [[0.47848372 0.64158664 0.5754506 ]
  [0.36223665 0.72767386 0.63369863]
  [0.90481633 0.13516732 0.94675037]
  [0.44921368 0.7429944  0.16132503]]]


In [12]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

mx_min_arr = np.random.random((10,10))
print(mx_min_arr)

print("Min value is: ", mx_min_arr.min())
print("Max value is: ", mx_min_arr.max())


[[0.43177624 0.95141684 0.14932249 0.3442979  0.66247988 0.75927339
  0.45969575 0.64112236 0.74075295 0.60910234]
 [0.63562093 0.02103413 0.83384029 0.27801572 0.00723325 0.45832958
  0.93233239 0.64932851 0.03558611 0.13993227]
 [0.11458641 0.02639426 0.08904127 0.33451541 0.66283408 0.91724409
  0.06831659 0.48803009 0.28306755 0.04431234]
 [0.05064511 0.61296916 0.45373401 0.63839916 0.63958181 0.03774514
  0.96123947 0.56035771 0.10306353 0.29749095]
 [0.53077361 0.03316382 0.5188554  0.4626939  0.92108858 0.12124767
  0.46630843 0.34942194 0.68920655 0.85851549]
 [0.11387429 0.66677057 0.49522554 0.57936553 0.17463305 0.68468847
  0.78838246 0.67800197 0.0574371  0.61551574]
 [0.35608975 0.606433   0.40010598 0.91983293 0.93558262 0.93401594
  0.04949008 0.66014988 0.45624165 0.40529099]
 [0.43514665 0.22719395 0.41189593 0.61989983 0.53063123 0.26178434
  0.3189534  0.73680573 0.87240258 0.7529579 ]
 [0.91656936 0.24057337 0.67143997 0.05285502 0.27357597 0.57970792
  0.52589609

In [13]:
# 14. Create a random vector of size 30 and find the mean value

ran_vec = np.random.random((30))
print(ran_vec)

print("min vector value is: ", ran_vec.min())

[0.24267955 0.18713125 0.71016955 0.99672009 0.70071008 0.36184345
 0.82076423 0.29808112 0.2193551  0.6670054  0.43649981 0.43486308
 0.29344798 0.9560662  0.86230714 0.77454831 0.74277296 0.52924221
 0.46930336 0.12182064 0.13296732 0.59059627 0.18592505 0.28380946
 0.59604559 0.74582486 0.95526046 0.41283474 0.53729492 0.54902688]
min vector value is:  0.12182064237762447


In [14]:
# 15. Create a 2d array with 1 on the border and 0 inside

twoDarr = np.ones((5,5))

twoDarr[1:-1, 1:-1] = 0
print(twoDarr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# 16. How to add a border (filled with 0's) around an existing array?
twoD = np.zeros((5,5))
print(twoD)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
diag = np.diag([1,2,3,4], k= -1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [17]:
# 18  Create a 8x8 matrix and fill it with a checkerboard pattern

checkboard = np.zeros((8,8), dtype= int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [18]:
# another way

cbd = np.indices((8,8)).sum(axis= 0) % 2
print(cbd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
# 20 Create a checkerboard 8x8 matrix using the tile function

tileprob = np.array([[1,0],
					[0,1]])
answ = np.tile(tileprob, (8,8))
print(answ)

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [20]:
# 21 Normalize a 5x5 random matrix 
orgarr = np.random.random((5,5))

norarr = (orgarr - orgarr.min() / orgarr.max() - orgarr.min())


print("Original Array: ", orgarr)
print("\nNormalized Array: ", norarr)


Original Array:  [[0.8109478  0.94040142 0.13707179 0.52487667 0.30753172]
 [0.82442862 0.78736411 0.88075781 0.5480131  0.52217952]
 [0.15728911 0.56433729 0.72695232 0.57305967 0.41719656]
 [0.45406353 0.55617005 0.70694438 0.21708203 0.52513263]
 [0.23144165 0.70864362 0.27872085 0.40764106 0.2544209 ]]

Normalized Array:  [[ 0.5281172   0.65757082 -0.14575881  0.24204607  0.02470112]
 [ 0.54159802  0.50453351  0.59792721  0.2651825   0.23934892]
 [-0.12554149  0.28150669  0.44412172  0.29022908  0.13436597]
 [ 0.17123293  0.27333945  0.42411378 -0.06574857  0.24230203]
 [-0.05138895  0.42581303 -0.00410975  0.12481046 -0.0284097 ]]


In [21]:
# 23

color_dtype = np.dtype([
	('R', np.uint8),
	('G', np.uint8),
	('B', np.uint8),
	('A', np.uint8)
])

In [22]:
color = np.array((255, 128, 64, 255), dtype= color_dtype)
print(color)

(255, 128, 64, 255)


In [23]:
print(color['R'])

255


In [24]:
# 24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

m1 = np.random.random((5, 3))
m2 = np.random.random((3, 2))

res = np.dot(m1, m2)

print("Matrix A: ", m1)
print("Matrix B: ", m2)
print("Matrix product: ", res)

Matrix A:  [[0.42695526 0.30448016 0.75695052]
 [0.34660598 0.36970399 0.82194421]
 [0.21560595 0.64141199 0.98926252]
 [0.51076008 0.35461133 0.33840799]
 [0.56244387 0.83778919 0.61963001]]
Matrix B:  [[0.11342419 0.93529827]
 [0.88759626 0.09939747]
 [0.99934904 0.09203135]]
Matrix product:  [[1.07514028 0.49925826]
 [1.18887054 0.43657225]
 [1.58238836 0.35645377]
 [0.71087194 0.54410463]
 [1.42663995 0.6663523 ]]


In [25]:
# 25 
arrneg = np.array([1, 4, 6, 9, 2, 7, 8, 3])

arrneg[(arrneg > 3) & (arrneg < 8)] *= -1

print(arrneg)


[ 1 -4 -6  9  2 -7  8  3]


In [26]:
# 27

z = np.array([1,2,3])

print(z**z) # legal

[ 1  4 27]


In [27]:
# 28

test = np.array([np.nan]).astype(int).astype(float)

print(test)

[-9.22337204e+18]


C:\Users\santosh\AppData\Local\Temp\ipykernel_26464\1949928742.py:3: RuntimeWarning: invalid value encountered in cast
  test = np.array([np.nan]).astype(int).astype(float)


In [28]:
# 29
roundarr = np.array([1.2, -2.1, 3.1, -4.2, 2.3, -1.1])

rounded = np.sign(roundarr) * np.ceil(np.abs(roundarr))

print(rounded)

[ 2. -3.  4. -5.  3. -2.]


In [29]:
# 30
A = np.array([1,2,9,8,5])
B = np.array([6,7,8,9,10])

common = np.intersect1d(A, B)
print(common)

[8 9]


In [30]:
# 31 How to ignore all numpy warnings (not recommended)?
# ignp = np.seterr(all='ignore')

from datetime import date, timedelta

In [31]:


today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)

Yesterday:  2026-02-03
Today:  2026-02-04
Tomorrow:  2026-02-05


In [32]:
# 34 How to get all the dates corresponding to the month of July 2016?
start = date(2016, 7, 1)
end = date(2016, 8, 1)

dates = []
current = start

while (current < end):
	dates.append(current)
	current += timedelta(days=1)

print(dates)

[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


In [33]:
# 36  Extract the integer part of a random array of positive numbers using 4 different methods
arr = np.random.random(5) * 10
print(arr)

[2.4115222  5.28291548 5.11618382 6.82894212 8.00752635]


In [34]:
# 1. using floor

arrfloor = np.floor(arr)
print(arrfloor)

# 2. using astype

arrtype = arr.astype(int)
print(arrtype)


[2. 5. 5. 6. 8.]
[2 5 5 6 8]


In [35]:
# 3. using trunc

arrtrunc = np.trunc(arr)

print(arrtrunc)

[2. 5. 5. 6. 8.]


In [36]:
# 4. using int divison

arrdivision = arr // 1

print(arrdivision)

[2. 5. 5. 6. 8.]


In [37]:
# 37 Create a 5x5 matrix with row values ranging from 0 to 4 

arrtile = np.tile(np.arange(5), (5,1))
print(arrtile)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [38]:
# 38 Consider a generator function that generates 10 integers and use it to build an array
def gen_gerenter():
	for i in range(10):
		yield i

In [39]:
gen_num = np.fromiter(gen_gerenter(), dtype=int)
print(gen_num)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 39
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
