In [13]:
import numpy as np

In [14]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [15]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [16]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [19]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [30]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

# option 2

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# 12. Create a 3x3x3 array with random values

random_arr = np.random.random((3,4,3))
print(random_arr)

[[[0.88301931 0.93530463 0.01577123]
  [0.83566962 0.67259988 0.11721844]
  [0.96363125 0.74007042 0.31403582]
  [0.06113415 0.82087845 0.98652362]]

 [[0.730102   0.03561232 0.50528032]
  [0.74918945 0.1355181  0.58438422]
  [0.2868556  0.68588781 0.4983482 ]
  [0.60310385 0.26716105 0.49870098]]

 [[0.74547842 0.19517616 0.17862502]
  [0.46661255 0.72730337 0.93501113]
  [0.68394203 0.79530039 0.66923453]
  [0.63736287 0.38060652 0.54528052]]]


In [42]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

mx_min_arr = np.random.random((10,10))
print(mx_min_arr)

print("Min value is: ", mx_min_arr.min())
print("Max value is: ", mx_min_arr.max())


[[0.64427816 0.8283885  0.83061428 0.19685892 0.4061673  0.48539092
  0.60655034 0.09232725 0.55461143 0.29384352]
 [0.86712085 0.04697371 0.01381949 0.01856812 0.53809563 0.38431467
  0.75255115 0.77425661 0.08631389 0.50207757]
 [0.61590704 0.17280299 0.89026105 0.50469426 0.50679522 0.29419916
  0.93185051 0.02120025 0.40398706 0.4250852 ]
 [0.21093938 0.69285784 0.88789363 0.09977415 0.06435157 0.52835842
  0.90778435 0.76394453 0.95020645 0.62909824]
 [0.04401006 0.17956514 0.22185606 0.09059422 0.27878127 0.71823015
  0.14086071 0.74356222 0.78458844 0.67970837]
 [0.01555377 0.98894921 0.31048722 0.36380915 0.28254007 0.93558163
  0.46308699 0.74477081 0.38189847 0.21159774]
 [0.29947209 0.16992243 0.73718619 0.98383018 0.81858833 0.53754666
  0.88255664 0.38178223 0.54857109 0.76620282]
 [0.32069808 0.45432138 0.85948083 0.69802871 0.4703433  0.60526183
  0.79064025 0.3898833  0.2866968  0.97056619]
 [0.39748351 0.22817226 0.82582117 0.63620775 0.2072623  0.42990592
  0.37905334