In [57]:
import numpy as np

In [58]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [59]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [60]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [61]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [62]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [63]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [64]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

# option 2

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
# 12. Create a 3x3x3 array with random values

random_arr = np.random.random((3,4,3))
print(random_arr)

[[[0.35990038 0.15410558 0.63128065]
  [0.24943612 0.07496164 0.75847101]
  [0.6206479  0.11518713 0.46776059]
  [0.37713224 0.77019601 0.80029851]]

 [[0.05202188 0.81107967 0.06965914]
  [0.54948253 0.06125999 0.07207635]
  [0.31545797 0.70515521 0.89697852]
  [0.84199796 0.32925709 0.66280759]]

 [[0.27364808 0.06166017 0.45711785]
  [0.71863128 0.88862483 0.14319567]
  [0.66315918 0.81503162 0.65412418]
  [0.40740334 0.89926561 0.6274539 ]]]


In [66]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

mx_min_arr = np.random.random((10,10))
print(mx_min_arr)

print("Min value is: ", mx_min_arr.min())
print("Max value is: ", mx_min_arr.max())


[[0.73564743 0.21274208 0.62555368 0.27288351 0.59283471 0.83007107
  0.76618986 0.97494103 0.89577962 0.33166767]
 [0.80969331 0.96753172 0.99491477 0.17181329 0.30498204 0.34988473
  0.3390026  0.88602359 0.30391322 0.99501188]
 [0.31593087 0.49293277 0.63668053 0.14908162 0.56713909 0.03899063
  0.21470388 0.18032497 0.54361545 0.88217551]
 [0.90733711 0.65072498 0.01836943 0.56402589 0.21744538 0.68723426
  0.29651296 0.0360689  0.6329531  0.75599879]
 [0.9358437  0.02745274 0.00131365 0.99287333 0.31977851 0.14793474
  0.60790876 0.15177614 0.39622295 0.22691506]
 [0.29783727 0.6996079  0.07613019 0.45908803 0.53665081 0.78146374
  0.95069815 0.86004967 0.64129817 0.28099356]
 [0.0185648  0.99008199 0.89654625 0.27362622 0.60595661 0.20485919
  0.61802243 0.80777985 0.68770742 0.7759228 ]
 [0.78674977 0.09764145 0.42638799 0.48205933 0.83923726 0.08621556
  0.54361363 0.15867348 0.63202282 0.21657637]
 [0.61869048 0.20999467 0.5267046  0.18828684 0.44948443 0.20026008
  0.06344834

In [67]:
# 14. Create a random vector of size 30 and find the mean value

ran_vec = np.random.random((30))
print(ran_vec)

print("min vector value is: ", ran_vec.min())

[0.7421558  0.0327095  0.80083339 0.88076888 0.23913914 0.9599721
 0.2887089  0.84995758 0.04904959 0.52745029 0.93224734 0.71357701
 0.31850245 0.72762608 0.02133914 0.12207327 0.98610669 0.89947332
 0.68153457 0.28572286 0.24871356 0.18774582 0.73840892 0.69540691
 0.71057567 0.07169732 0.85797249 0.87803503 0.43221977 0.71990337]
min vector value is:  0.021339135668399845


In [68]:
# 15. Create a 2d array with 1 on the border and 0 inside

twoDarr = np.ones((5,5))

twoDarr[1:-1, 1:-1] = 0
print(twoDarr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
# 16. How to add a border (filled with 0's) around an existing array?
twoD = np.zeros((5,5))
print(twoD)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [70]:
diag = np.diag([1,2,3,4], k= -1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [71]:
# 18  Create a 8x8 matrix and fill it with a checkerboard pattern

checkboard = np.zeros((8,8), dtype= int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [72]:
# another way

cbd = np.indices((8,8)).sum(axis= 0) % 2
print(cbd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [73]:
# 20 Create a checkerboard 8x8 matrix using the tile function

tileprob = np.array([[1,0],
					[0,1]])
answ = np.tile(tileprob, (8,8))
print(answ)

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [74]:
# 21 Normalize a 5x5 random matrix 
orgarr = np.random.random((5,5))

norarr = (orgarr - orgarr.min() / orgarr.max() - orgarr.min())


print("Original Array: ", orgarr)
print("\nNormalized Array: ", norarr)


Original Array:  [[0.76050199 0.1386737  0.16269915 0.87788151 0.53912534]
 [0.48413974 0.7423802  0.92375832 0.42071039 0.79796214]
 [0.92802092 0.13135663 0.86226897 0.64518759 0.71796456]
 [0.61351662 0.57298585 0.86625463 0.90782076 0.6842725 ]
 [0.60083845 0.78148433 0.15432936 0.25688317 0.63512883]]

Normalized Array:  [[ 0.48760045 -0.13422784 -0.11020239  0.60497997  0.2662238 ]
 [ 0.2112382   0.46947866  0.65085678  0.14780885  0.5250606 ]
 [ 0.65511937 -0.14154491  0.58936743  0.37228605  0.44506302]
 [ 0.34061508  0.30008431  0.59335309  0.63491922  0.41137096]
 [ 0.32793691  0.50858279 -0.11857218 -0.01601837  0.36222729]]


In [75]:
# 23

color_dtype = np.dtype([
	('R', np.uint8),
	('G', np.uint8),
	('B', np.uint8),
	('A', np.uint8)
])

In [76]:
color = np.array((255, 128, 64, 255), dtype= color_dtype)
print(color)

(255, 128, 64, 255)


In [77]:
print(color['R'])

255


In [78]:
# 24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

m1 = np.random.random((5, 3))
m2 = np.random.random((3, 2))

res = np.dot(m1, m2)

print("Matrix A: ", m1)
print("Matrix B: ", m2)
print("Matrix product: ", res)

Matrix A:  [[0.64257886 0.85995102 0.79557439]
 [0.54814448 0.28945894 0.1852604 ]
 [0.97374243 0.75092634 0.44063924]
 [0.76563324 0.6297608  0.71341897]
 [0.11805434 0.71121693 0.94052188]]
Matrix B:  [[0.82333957 0.81656737]
 [0.88891128 0.40463708]
 [0.72719231 0.22572537]]
Matrix product:  [[1.87201634 1.05225833]
 [0.8433323  0.60654069]
 [1.78965704 1.1984424 ]
 [1.70897042 1.04105246]
 [1.41334785 0.59648372]]


In [79]:
# 25 
arrneg = np.array([1, 4, 6, 9, 2, 7, 8, 3])

arrneg[(arrneg > 3) & (arrneg < 8)] *= -1

print(arrneg)


[ 1 -4 -6  9  2 -7  8  3]


In [80]:
# 27

z = np.array([1,2,3])

print(z**z) # legal

[ 1  4 27]


In [81]:
# 28

test = np.array([np.nan]).astype(int).astype(float)

print(test)

[-9.22337204e+18]


C:\Users\santosh\AppData\Local\Temp\ipykernel_6424\1949928742.py:3: RuntimeWarning: invalid value encountered in cast
  test = np.array([np.nan]).astype(int).astype(float)


In [82]:
# 29
roundarr = np.array([1.2, -2.1, 3.1, -4.2, 2.3, -1.1])

rounded = np.sign(roundarr) * np.ceil(np.abs(roundarr))

print(rounded)

[ 2. -3.  4. -5.  3. -2.]


In [83]:
# 30
A = np.array([1,2,9,8,5])
B = np.array([6,7,8,9,10])

common = np.intersect1d(A, B)
print(common)

[8 9]


In [84]:
# 31 How to ignore all numpy warnings (not recommended)?
# ignp = np.seterr(all='ignore')

from datetime import date, timedelta

In [85]:


today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)

Yesterday:  2026-02-11
Today:  2026-02-12
Tomorrow:  2026-02-13


In [86]:
# 34 How to get all the dates corresponding to the month of July 2016?
start = date(2016, 7, 1)
end = date(2016, 8, 1)

dates = []
current = start

while (current < end):
	dates.append(current)
	current += timedelta(days=1)

print(dates)

[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


In [87]:
# 36  Extract the integer part of a random array of positive numbers using 4 different methods
arr = np.random.random(5) * 10
print(arr)

[8.39595215 8.67511741 6.30888916 8.00685996 8.82253051]


In [88]:
# 1. using floor

arrfloor = np.floor(arr)
print(arrfloor)

# 2. using astype

arrtype = arr.astype(int)
print(arrtype)


[8. 8. 6. 8. 8.]
[8 8 6 8 8]


In [89]:
# 3. using trunc

arrtrunc = np.trunc(arr)

print(arrtrunc)

[8. 8. 6. 8. 8.]


In [90]:
# 4. using int divison

arrdivision = arr // 1

print(arrdivision)

[8. 8. 6. 8. 8.]


In [91]:
# 37 Create a 5x5 matrix with row values ranging from 0 to 4 

arrtile = np.tile(np.arange(5), (5,1))
print(arrtile)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [92]:
# 38 Consider a generator function that generates 10 integers and use it to build an array
def gen_gerenter():
	for i in range(10):
		yield i

In [93]:
gen_num = np.fromiter(gen_gerenter(), dtype=int)
print(gen_num)

[0 1 2 3 4 5 6 7 8 9]


In [94]:
# 39
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [95]:
# 40 Create a random vector of size 10 and sort it

rvec = np.random.random(10)
srt = np.sort(rvec)

print("Original array: ",rvec)
print("Sorted array: ",srt)

Original array:  [0.04259871 0.67918426 0.61206565 0.29089693 0.6211967  0.40360945
 0.45164246 0.5916243  0.47736093 0.70315514]
Sorted array:  [0.04259871 0.29089693 0.40360945 0.45164246 0.47736093 0.5916243
 0.61206565 0.6211967  0.67918426 0.70315514]


In [96]:
# 41  How to sum a small array faster than np.sum?

samplearr = np.array([1,2,3,4,5])

# using numpy
npsum = np.sum(samplearr)
print(npsum)

# using built-in 
bisum = sum(samplearr)
print(bisum)

15
15


In [97]:
# 42 Consider two random arrays A and B, check if they are equal

A = np.random.random(5)
B = np.random.random(5)

isequal = np.allclose(A, B)

print(isequal)

False


In [98]:
# 43 Make an array immutable (read-only) 

arr = np.array([1,2,3,4,5])
imutable = arr.flags.writeable = False


In [99]:
# 45  Create random vector of size 10 and replace the maximum value by 0

arr = np.random.random((10))

vec = arr.argmax()

arr[vec] = 0

print(arr)

[0.34644161 0.61215096 0.67736975 0.76307863 0.47158096 0.91873002
 0.         0.80675007 0.04610999 0.88565218]


In [100]:
# 46  Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

x = np.linspace(0,1, 5)
y = np.linspace(0,1, 5)

x, y = np.meshgrid(x, y)

z = np.zeros(x.size, dtype=[('x', float), ('y', float)])

z['x'] = x.ravel()
z['y'] = y.ravel()

print(z)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


In [101]:
# 48

int_types = [np.int8, np.int16, np.int32, np.int64, np.uint, np.uint8, np.uint16, np.uint32, np.uint64]

print("Integer Types: ")
for t in int_types:
	info = np.iinfo(t)
	print(f"{t.__name__}: min={info.min}, max={info.max}")
	

Integer Types: 
int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint64: min=0, max=18446744073709551615
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615


In [102]:
# for floating value

float_types = [np.float16, np.float32, np.float64]

print("Floating values: ")
for f in float_types:
	info = np.finfo(f)
	print(f"{f.__name__}: min={info.min}, max={info.max}")

Floating values: 
float16: min=-65504.0, max=65504.0
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


In [103]:
# 50  How to find the closest value (to a given scalar) in a vector?

vec = np.array([2.0, 4.2, 5.32, 6.87])
value = 5.11

closet = vec[np.abs(vec - value).argmin()]

print(closet)

5.32


In [104]:
# 51 
import numpy as np

dtype = np.dtype([
    ('position', [('x', 'f4'), ('y', 'f4')]),
    ('color',    [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])
])


data = np.array([
    ((0.1, 0.2), (255, 0, 0)),    # red
    ((0.4, 0.6), (0, 255, 0)),    # green
    ((0.8, 0.9), (0, 0, 255))     # blue
], dtype=dtype)


print(data)


[((0.1, 0.2), (255,   0,   0)) ((0.4, 0.6), (  0, 255,   0))
 ((0.8, 0.9), (  0,   0, 255))]


In [105]:
# 52
Z = np.random.random((100, 2))

distances = np.sqrt(Z[:, 0]**2 + Z[:, 1]**2)

print(distances)

[1.0642917  0.56232152 1.01451537 0.88790183 0.97119156 0.86236266
 1.22335043 1.01505136 0.46615878 0.94211312 0.45213361 0.82492514
 0.92474023 0.74800466 1.17993366 0.90953941 0.89088142 0.18916154
 1.00166727 0.21919014 0.71439293 0.20506394 0.2864421  0.88327365
 0.20928241 0.75425544 1.02874366 0.94855766 0.28340046 0.94556132
 0.58990751 0.39067345 0.78397496 0.37000572 1.05648271 0.89518018
 0.79939863 0.1972162  0.1260885  0.94476909 0.53231467 0.61707919
 1.15235406 0.29206703 0.50059408 0.36100258 1.05528526 0.9853151
 0.71324184 0.69847907 0.95737033 0.75841385 0.66082953 0.91955159
 0.96124521 0.75643272 0.3493169  1.06144067 0.46329697 0.8699411
 0.41995341 0.55876633 0.33274782 0.3882455  0.95113831 1.01625617
 0.21996028 0.6316034  0.8550035  1.21737052 0.69610319 1.03917238
 0.81559304 0.67851949 1.04860532 0.48567873 1.08341104 0.61123266
 0.61592744 0.86085815 1.31871715 0.72311685 1.00726929 0.78143792
 0.87039419 1.11343012 0.91196636 0.99100345 0.59714221 0.478173

In [106]:
# 53 
A = np.random.random(5).astype(np.float32)

A.dtype = np.int32

print(A)

[1037759836 1055461058 1052933517 1055694293 1048800455]


In [109]:
# 55
arr = np.array([10, 20, 30])

for index, value in enumerate(arr):
    print(index, value)

0 10
1 20
2 30
