In [1]:
import numpy as np

In [2]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [3]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [4]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [8]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

# option 2

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# 12. Create a 3x3x3 array with random values

random_arr = np.random.random((3,4,3))
print(random_arr)

[[[0.84192239 0.83357191 0.49674404]
  [0.39354578 0.76882769 0.71164677]
  [0.908445   0.98807201 0.52960277]
  [0.52593237 0.40079521 0.61088832]]

 [[0.08834148 0.88035083 0.73947445]
  [0.51461085 0.98411278 0.20398636]
  [0.7987321  0.30018    0.75631663]
  [0.34505566 0.54829733 0.22924598]]

 [[0.65648547 0.42935601 0.92915218]
  [0.78091987 0.97526677 0.79242249]
  [0.89768378 0.6258404  0.99873144]
  [0.12419047 0.10149232 0.88119938]]]


In [10]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

mx_min_arr = np.random.random((10,10))
print(mx_min_arr)

print("Min value is: ", mx_min_arr.min())
print("Max value is: ", mx_min_arr.max())


[[0.83343974 0.3934482  0.86652405 0.88030418 0.80113072 0.93883353
  0.53839258 0.75330869 0.0398048  0.82057489]
 [0.17923987 0.74307893 0.17734351 0.31890488 0.22653814 0.94322194
  0.69171514 0.81115446 0.81594395 0.3306307 ]
 [0.02528109 0.27265197 0.81207435 0.11402837 0.43121164 0.22750845
  0.34054779 0.74334775 0.61874845 0.15855996]
 [0.07632181 0.40924439 0.52615765 0.76850299 0.96302499 0.50700105
  0.20592768 0.43122116 0.83498116 0.84878334]
 [0.16148723 0.7411289  0.39897923 0.83672686 0.6549055  0.36259352
  0.28907589 0.32876043 0.64116993 0.58100036]
 [0.15465165 0.49418118 0.74266739 0.13885233 0.60677348 0.51468851
  0.30423864 0.78085367 0.54243681 0.28996393]
 [0.85039851 0.03215185 0.2926303  0.02431252 0.13485671 0.90238331
  0.4043193  0.29838044 0.90750765 0.02829019]
 [0.93053589 0.21390816 0.29257115 0.94493393 0.0657653  0.16723474
  0.78235521 0.2022369  0.31196721 0.76125498]
 [0.14353729 0.12943994 0.62951415 0.41497513 0.76329385 0.50062963
  0.07559886

In [11]:
# 14. Create a random vector of size 30 and find the mean value

ran_vec = np.random.random((30))
print(ran_vec)

print("min vector value is: ", ran_vec.min())

[0.74035924 0.86044399 0.11877579 0.0356363  0.58900369 0.55251773
 0.37526054 0.87080123 0.63422293 0.93433712 0.16796779 0.70340392
 0.55213756 0.27174223 0.85718335 0.52886091 0.00519324 0.03719275
 0.53052595 0.74102974 0.50089023 0.63645404 0.34808807 0.73699076
 0.07861494 0.72339023 0.51579237 0.51557859 0.59604044 0.99303967]
min vector value is:  0.005193239595547294


In [12]:
# 15. Create a 2d array with 1 on the border and 0 inside

twoDarr = np.ones((5,5))

twoDarr[1:-1, 1:-1] = 0
print(twoDarr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# 16. How to add a border (filled with 0's) around an existing array?
twoD = np.zeros((5,5))
print(twoD)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
diag = np.diag([1,2,3,4], k= -1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [15]:
# 18  Create a 8x8 matrix and fill it with a checkerboard pattern

checkboard = np.zeros((8,8), dtype= int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [16]:
# another way

cbd = np.indices((8,8)).sum(axis= 0) % 2
print(cbd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# 20 Create a checkerboard 8x8 matrix using the tile function

tileprob = np.array([[1,0],
					[0,1]])
answ = np.tile(tileprob, (8,8))
print(answ)

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [18]:
# 21 Normalize a 5x5 random matrix 
orgarr = np.random.random((5,5))

norarr = (orgarr - orgarr.min() / orgarr.max() - orgarr.min())


print("Original Array: ", orgarr)
print("\nNormalized Array: ", norarr)


Original Array:  [[0.35331193 0.58519155 0.35489508 0.33395124 0.36171523]
 [0.11817726 0.73693436 0.99725528 0.55693769 0.23101693]
 [0.15189698 0.48516303 0.18160596 0.41376409 0.07750907]
 [0.05532151 0.34093225 0.04126621 0.50801351 0.48651735]
 [0.98480076 0.64230943 0.55450656 0.85471623 0.87164424]]

Normalized Array:  [[ 0.27066593  0.50254555  0.27224908  0.25130524  0.27906922]
 [ 0.03553125  0.65428836  0.91460928  0.47429168  0.14837093]
 [ 0.06925097  0.40251703  0.09895995  0.33111809 -0.00513694]
 [-0.0273245   0.25828625 -0.04137979  0.42536751  0.40387134]
 [ 0.90215476  0.55966343  0.47186055  0.77207023  0.78899823]]


In [19]:
# 23

color_dtype = np.dtype([
	('R', np.uint8),
	('G', np.uint8),
	('B', np.uint8),
	('A', np.uint8)
])

In [20]:
color = np.array((255, 128, 64, 255), dtype= color_dtype)
print(color)

(255, 128, 64, 255)


In [21]:
print(color['R'])

255


In [22]:
# 24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

m1 = np.random.random((5, 3))
m2 = np.random.random((3, 2))

res = np.dot(m1, m2)

print("Matrix A: ", m1)
print("Matrix B: ", m2)
print("Matrix product: ", res)

Matrix A:  [[0.32925268 0.09876787 0.49967865]
 [0.04833534 0.38271781 0.7531418 ]
 [0.29153994 0.5251561  0.89100656]
 [0.74217677 0.73899691 0.76987432]
 [0.97199209 0.38403791 0.48857266]]
Matrix B:  [[0.06787313 0.47072583]
 [0.27498005 0.67231463]
 [0.03309442 0.52359119]]
Matrix product:  [[0.06604318 0.48301817]
 [0.13344522 0.67439788]
 [0.19368252 0.95682869]
 [0.27906181 1.24929962]
 [0.18774394 0.97154843]]


In [23]:
# 25 
arrneg = np.array([1, 4, 6, 9, 2, 7, 8, 3])

arrneg[(arrneg > 3) & (arrneg < 8)] *= -1

print(arrneg)


[ 1 -4 -6  9  2 -7  8  3]


In [24]:
# 27

z = np.array([1,2,3])

print(z**z) # legal

[ 1  4 27]


In [25]:
# 28

test = np.array([np.nan]).astype(int).astype(float)

print(test)

[-9.22337204e+18]


C:\Users\santosh\AppData\Local\Temp\ipykernel_17176\1949928742.py:3: RuntimeWarning: invalid value encountered in cast
  test = np.array([np.nan]).astype(int).astype(float)


In [26]:
# 29
roundarr = np.array([1.2, -2.1, 3.1, -4.2, 2.3, -1.1])

rounded = np.sign(roundarr) * np.ceil(np.abs(roundarr))

print(rounded)

[ 2. -3.  4. -5.  3. -2.]


In [27]:
# 30
A = np.array([1,2,9,8,5])
B = np.array([6,7,8,9,10])

common = np.intersect1d(A, B)
print(common)

[8 9]


In [28]:
# 31 How to ignore all numpy warnings (not recommended)?
# ignp = np.seterr(all='ignore')

from datetime import date, timedelta

In [29]:


today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)

Yesterday:  2026-02-06
Today:  2026-02-07
Tomorrow:  2026-02-08


In [30]:
# 34 How to get all the dates corresponding to the month of July 2016?
start = date(2016, 7, 1)
end = date(2016, 8, 1)

dates = []
current = start

while (current < end):
	dates.append(current)
	current += timedelta(days=1)

print(dates)

[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


In [31]:
# 36  Extract the integer part of a random array of positive numbers using 4 different methods
arr = np.random.random(5) * 10
print(arr)

[3.27733216 4.93665547 1.11953342 4.42948182 0.89769622]


In [32]:
# 1. using floor

arrfloor = np.floor(arr)
print(arrfloor)

# 2. using astype

arrtype = arr.astype(int)
print(arrtype)


[3. 4. 1. 4. 0.]
[3 4 1 4 0]


In [33]:
# 3. using trunc

arrtrunc = np.trunc(arr)

print(arrtrunc)

[3. 4. 1. 4. 0.]


In [34]:
# 4. using int divison

arrdivision = arr // 1

print(arrdivision)

[3. 4. 1. 4. 0.]


In [35]:
# 37 Create a 5x5 matrix with row values ranging from 0 to 4 

arrtile = np.tile(np.arange(5), (5,1))
print(arrtile)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [36]:
# 38 Consider a generator function that generates 10 integers and use it to build an array
def gen_gerenter():
	for i in range(10):
		yield i

In [37]:
gen_num = np.fromiter(gen_gerenter(), dtype=int)
print(gen_num)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
# 39
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [39]:
# 40 Create a random vector of size 10 and sort it

rvec = np.random.random(10)
srt = np.sort(rvec)

print("Original array: ",rvec)
print("Sorted array: ",srt)

Original array:  [0.25839206 0.36296124 0.26021416 0.72683473 0.96316802 0.89513561
 0.64764441 0.20694463 0.10098786 0.29791632]
Sorted array:  [0.10098786 0.20694463 0.25839206 0.26021416 0.29791632 0.36296124
 0.64764441 0.72683473 0.89513561 0.96316802]


In [40]:
# 41  How to sum a small array faster than np.sum?

samplearr = np.array([1,2,3,4,5])

# using numpy
npsum = np.sum(samplearr)
print(npsum)

# using built-in 
bisum = sum(samplearr)
print(bisum)

15
15


In [41]:
# 42 Consider two random arrays A and B, check if they are equal

A = np.random.random(5)
B = np.random.random(5)

isequal = np.allclose(A, B)

print(isequal)

False


In [42]:
# 43 Make an array immutable (read-only) 

arr = np.array([1,2,3,4,5])
imutable = arr.flags.writeable = False


In [43]:
# 45  Create random vector of size 10 and replace the maximum value by 0

arr = np.random.random((10))

vec = arr.argmax()

arr[vec] = 0

print(arr)

[0.64717233 0.62920456 0.44753675 0.54630652 0.         0.72355553
 0.53329332 0.29635732 0.35922559 0.48624932]


In [44]:
# 46  Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

x = np.linspace(0,1, 5)
y = np.linspace(0,1, 5)

x, y = np.meshgrid(x, y)

z = np.zeros(x.size, dtype=[('x', float), ('y', float)])

z['x'] = x.ravel()
z['y'] = y.ravel()

print(z)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


In [48]:
# 48

int_types = [np.int8, np.int16, np.int32, np.int64, np.uint, np.uint8, np.uint16, np.uint32, np.uint64]

print("Integer Types: ")
for t in int_types:
	info = np.iinfo(t)
	print(f"{t.__name__}: min={info.min}, max={info.max}")
	

Integer Types: 
int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint64: min=0, max=18446744073709551615
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615


In [50]:
# for floating value

float_types = [np.float16, np.float32, np.float64]

print("Floating values: ")
for f in float_types:
	info = np.finfo(f)
	print(f"{f.__name__}: min={info.min}, max={info.max}")

Floating values: 
float16: min=-65504.0, max=65504.0
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308
