In [1]:
import numpy as np

In [2]:
# 5. How to get the documentation of the numpy add function from the command line?

np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [3]:
# 6. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(5)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1.]


In [4]:
# 7. Create a vector with values ranging from 10 to 49
vect = np.arange(10, 50)
print(vect)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
# 8. Reverse a vector (first element becomes last) 
reverse1 = vect[::-1]
print(reverse1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3,3)

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
idx = np.array([1,2,0,0,4,0])

print(np.nonzero(idx))

(array([0, 1, 4]),)


In [8]:
# 11. Create a 3x3 identity matrix
ident_matrix = np.eye(3)
print(ident_matrix)

# option 2

I = np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# 12. Create a 3x3x3 array with random values

random_arr = np.random.random((3,4,3))
print(random_arr)

[[[0.78262072 0.05110056 0.53823195]
  [0.54542899 0.4649673  0.09137782]
  [0.02431553 0.40952372 0.54529438]
  [0.88487861 0.74886554 0.91949607]]

 [[0.58112218 0.16849615 0.66517893]
  [0.00863375 0.85142808 0.83668921]
  [0.7447385  0.44256004 0.00193372]
  [0.94335701 0.27007617 0.91621545]]

 [[0.84365417 0.43661164 0.15684743]
  [0.01021756 0.50744849 0.34050556]
  [0.11979896 0.00803384 0.15185828]
  [0.42534974 0.2825802  0.56566461]]]


In [10]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values 

mx_min_arr = np.random.random((10,10))
print(mx_min_arr)

print("Min value is: ", mx_min_arr.min())
print("Max value is: ", mx_min_arr.max())


[[5.53321399e-01 3.19227404e-01 5.09640500e-01 2.77254354e-01
  5.42727903e-01 8.36999796e-01 4.97087816e-01 5.16350443e-01
  9.85700785e-01 2.81036914e-01]
 [5.78045821e-01 1.85934935e-01 3.70039303e-01 9.33836621e-01
  9.08544995e-01 5.64580110e-01 6.72935344e-01 1.72486885e-01
  5.02419237e-01 6.88602750e-01]
 [4.51967215e-01 5.21085389e-01 7.85337072e-01 4.68480064e-02
  6.20152358e-01 6.28507299e-01 5.80805787e-01 2.06445194e-01
  1.67693735e-01 6.22376259e-01]
 [4.24761130e-01 9.12676078e-01 9.75528502e-01 6.12975987e-01
  4.78212679e-01 7.95389036e-01 9.56440122e-01 5.71457683e-01
  5.86742865e-01 9.17148592e-01]
 [7.83348897e-01 8.16036246e-01 5.69966314e-01 2.69173094e-01
  5.19886299e-01 2.72063643e-01 9.02581204e-01 3.84757492e-01
  2.73261644e-01 7.56981280e-01]
 [5.75231822e-01 9.19178321e-01 1.01880937e-01 7.50751923e-01
  8.47258665e-01 4.84837959e-01 7.99462596e-01 7.37685803e-04
  4.33171937e-01 9.49462188e-01]
 [8.45576073e-01 5.95693428e-01 1.78242716e-01 4.07910138e

In [11]:
# 14. Create a random vector of size 30 and find the mean value

ran_vec = np.random.random((30))
print(ran_vec)

print("min vector value is: ", ran_vec.min())

[0.88538112 0.00749418 0.95389665 0.57519152 0.6399739  0.8760855
 0.8175919  0.1376987  0.0434955  0.8382144  0.70946428 0.11307559
 0.73197788 0.60052355 0.10340215 0.08184734 0.39646102 0.76326563
 0.1362329  0.90377827 0.74059989 0.91212742 0.94676683 0.29873481
 0.09067851 0.73924577 0.696416   0.1070139  0.44408008 0.31840235]
min vector value is:  0.007494181861798066


In [12]:
# 15. Create a 2d array with 1 on the border and 0 inside

twoDarr = np.ones((5,5))

twoDarr[1:-1, 1:-1] = 0
print(twoDarr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# 16. How to add a border (filled with 0's) around an existing array?
twoD = np.zeros((5,5))
print(twoD)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
diag = np.diag([1,2,3,4], k= -1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [15]:
# 18  Create a 8x8 matrix and fill it with a checkerboard pattern

checkboard = np.zeros((8,8), dtype= int)
checkboard[::2, ::2] = 1
checkboard[1::2, 1::2] = 1
print(checkboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [16]:
# another way

cbd = np.indices((8,8)).sum(axis= 0) % 2
print(cbd)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
# 20 Create a checkerboard 8x8 matrix using the tile function

tileprob = np.array([[1,0],
					[0,1]])
answ = np.tile(tileprob, (8,8))
print(answ)

[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]]


In [18]:
# 21 Normalize a 5x5 random matrix 
orgarr = np.random.random((5,5))

norarr = (orgarr - orgarr.min() / orgarr.max() - orgarr.min())


print("Original Array: ", orgarr)
print("\nNormalized Array: ", norarr)


Original Array:  [[0.47182454 0.20260365 0.19865863 0.99456644 0.51303326]
 [0.05840598 0.00168586 0.00702329 0.97129829 0.07262262]
 [0.85874978 0.52313179 0.13364549 0.1604692  0.25532405]
 [0.37047991 0.64585224 0.35576217 0.49062891 0.11167083]
 [0.6137969  0.35838572 0.14681251 0.47431373 0.76845437]]

Normalized Array:  [[ 0.4684436   0.19922271  0.19527769  0.9911855   0.50965232]
 [ 0.05502504 -0.00169507  0.00364235  0.96791735  0.06924168]
 [ 0.85536884  0.51975085  0.13026455  0.15708826  0.25194311]
 [ 0.36709897  0.6424713   0.35238123  0.48724797  0.10828989]
 [ 0.61041596  0.35500478  0.14343157  0.47093279  0.76507343]]


In [19]:
# 23

color_dtype = np.dtype([
	('R', np.uint8),
	('G', np.uint8),
	('B', np.uint8),
	('A', np.uint8)
])

In [20]:
color = np.array((255, 128, 64, 255), dtype= color_dtype)
print(color)

(255, 128, 64, 255)


In [21]:
print(color['R'])

255


In [22]:
# 24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

m1 = np.random.random((5, 3))
m2 = np.random.random((3, 2))

res = np.dot(m1, m2)

print("Matrix A: ", m1)
print("Matrix B: ", m2)
print("Matrix product: ", res)

Matrix A:  [[0.61710409 0.67468444 0.40666466]
 [0.6754545  0.33126936 0.31350839]
 [0.5267333  0.59088934 0.37763698]
 [0.97884209 0.00864895 0.66148744]
 [0.7941056  0.33703871 0.17064708]]
Matrix B:  [[0.57143253 0.79940264]
 [0.4525895  0.86019176]
 [0.04551619 0.07718607]]
Matrix product:  [[0.67649828 1.10506148]
 [0.55017542 0.84911377]
 [0.58561145 0.95849844]
 [0.59336503 0.84098633]
 [0.61408516 0.93789961]]


In [23]:
# 25 
arrneg = np.array([1, 4, 6, 9, 2, 7, 8, 3])

arrneg[(arrneg > 3) & (arrneg < 8)] *= -1

print(arrneg)


[ 1 -4 -6  9  2 -7  8  3]


In [24]:
# 27

z = np.array([1,2,3])

print(z**z) # legal

[ 1  4 27]


In [25]:
# 28

test = np.array([np.nan]).astype(int).astype(float)

print(test)

[-9.22337204e+18]


C:\Users\santosh\AppData\Local\Temp\ipykernel_14220\1949928742.py:3: RuntimeWarning: invalid value encountered in cast
  test = np.array([np.nan]).astype(int).astype(float)


In [26]:
# 29
roundarr = np.array([1.2, -2.1, 3.1, -4.2, 2.3, -1.1])

rounded = np.sign(roundarr) * np.ceil(np.abs(roundarr))

print(rounded)

[ 2. -3.  4. -5.  3. -2.]


In [27]:
# 30
A = np.array([1,2,9,8,5])
B = np.array([6,7,8,9,10])

common = np.intersect1d(A, B)
print(common)

[8 9]


In [28]:
# 31 How to ignore all numpy warnings (not recommended)?
# ignp = np.seterr(all='ignore')

from datetime import date, timedelta

In [29]:


today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday: ",yesterday)
print("Today: ",today)
print("Tomorrow: ",tomorrow)

Yesterday:  2026-02-07
Today:  2026-02-08
Tomorrow:  2026-02-09


In [30]:
# 34 How to get all the dates corresponding to the month of July 2016?
start = date(2016, 7, 1)
end = date(2016, 8, 1)

dates = []
current = start

while (current < end):
	dates.append(current)
	current += timedelta(days=1)

print(dates)

[datetime.date(2016, 7, 1), datetime.date(2016, 7, 2), datetime.date(2016, 7, 3), datetime.date(2016, 7, 4), datetime.date(2016, 7, 5), datetime.date(2016, 7, 6), datetime.date(2016, 7, 7), datetime.date(2016, 7, 8), datetime.date(2016, 7, 9), datetime.date(2016, 7, 10), datetime.date(2016, 7, 11), datetime.date(2016, 7, 12), datetime.date(2016, 7, 13), datetime.date(2016, 7, 14), datetime.date(2016, 7, 15), datetime.date(2016, 7, 16), datetime.date(2016, 7, 17), datetime.date(2016, 7, 18), datetime.date(2016, 7, 19), datetime.date(2016, 7, 20), datetime.date(2016, 7, 21), datetime.date(2016, 7, 22), datetime.date(2016, 7, 23), datetime.date(2016, 7, 24), datetime.date(2016, 7, 25), datetime.date(2016, 7, 26), datetime.date(2016, 7, 27), datetime.date(2016, 7, 28), datetime.date(2016, 7, 29), datetime.date(2016, 7, 30), datetime.date(2016, 7, 31)]


In [31]:
# 36  Extract the integer part of a random array of positive numbers using 4 different methods
arr = np.random.random(5) * 10
print(arr)

[9.3424347  8.56460376 1.46208055 1.81440353 0.36015983]


In [32]:
# 1. using floor

arrfloor = np.floor(arr)
print(arrfloor)

# 2. using astype

arrtype = arr.astype(int)
print(arrtype)


[9. 8. 1. 1. 0.]
[9 8 1 1 0]


In [33]:
# 3. using trunc

arrtrunc = np.trunc(arr)

print(arrtrunc)

[9. 8. 1. 1. 0.]


In [34]:
# 4. using int divison

arrdivision = arr // 1

print(arrdivision)

[9. 8. 1. 1. 0.]


In [35]:
# 37 Create a 5x5 matrix with row values ranging from 0 to 4 

arrtile = np.tile(np.arange(5), (5,1))
print(arrtile)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [36]:
# 38 Consider a generator function that generates 10 integers and use it to build an array
def gen_gerenter():
	for i in range(10):
		yield i

In [37]:
gen_num = np.fromiter(gen_gerenter(), dtype=int)
print(gen_num)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
# 39
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [39]:
# 40 Create a random vector of size 10 and sort it

rvec = np.random.random(10)
srt = np.sort(rvec)

print("Original array: ",rvec)
print("Sorted array: ",srt)

Original array:  [0.02628396 0.31796631 0.18768049 0.00571538 0.22850169 0.68596908
 0.77227242 0.20544106 0.77188323 0.14185125]
Sorted array:  [0.00571538 0.02628396 0.14185125 0.18768049 0.20544106 0.22850169
 0.31796631 0.68596908 0.77188323 0.77227242]


In [40]:
# 41  How to sum a small array faster than np.sum?

samplearr = np.array([1,2,3,4,5])

# using numpy
npsum = np.sum(samplearr)
print(npsum)

# using built-in 
bisum = sum(samplearr)
print(bisum)

15
15


In [41]:
# 42 Consider two random arrays A and B, check if they are equal

A = np.random.random(5)
B = np.random.random(5)

isequal = np.allclose(A, B)

print(isequal)

False


In [42]:
# 43 Make an array immutable (read-only) 

arr = np.array([1,2,3,4,5])
imutable = arr.flags.writeable = False


In [43]:
# 45  Create random vector of size 10 and replace the maximum value by 0

arr = np.random.random((10))

vec = arr.argmax()

arr[vec] = 0

print(arr)

[0.         0.51188526 0.02824358 0.20249434 0.42367306 0.09246779
 0.0932713  0.03779493 0.17009631 0.10203072]


In [44]:
# 46  Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

x = np.linspace(0,1, 5)
y = np.linspace(0,1, 5)

x, y = np.meshgrid(x, y)

z = np.zeros(x.size, dtype=[('x', float), ('y', float)])

z['x'] = x.ravel()
z['y'] = y.ravel()

print(z)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


In [45]:
# 48

int_types = [np.int8, np.int16, np.int32, np.int64, np.uint, np.uint8, np.uint16, np.uint32, np.uint64]

print("Integer Types: ")
for t in int_types:
	info = np.iinfo(t)
	print(f"{t.__name__}: min={info.min}, max={info.max}")
	

Integer Types: 
int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint64: min=0, max=18446744073709551615
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615


In [46]:
# for floating value

float_types = [np.float16, np.float32, np.float64]

print("Floating values: ")
for f in float_types:
	info = np.finfo(f)
	print(f"{f.__name__}: min={info.min}, max={info.max}")

Floating values: 
float16: min=-65504.0, max=65504.0
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


In [47]:
# 50  How to find the closest value (to a given scalar) in a vector?

vec = np.array([2.0, 4.2, 5.32, 6.87])
value = 5.11

closet = vec[np.abs(vec - value).argmin()]

print(closet)

5.32


In [ ]:
# 51 
import numpy as np

dtype = np.dtype([
    ('position', [('x', 'f4'), ('y', 'f4')]),
    ('color',    [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])
])

data = np.array([
    ((0.1, 0.2), (255, 0, 0)),    # red
    ((0.4, 0.6), (0, 255, 0)),    # green
    ((0.8, 0.9), (0, 0, 255))     # blue
], dtype=dtype)

print(data)
